httpdns/app.py
#!/usr/bin/env python
# encoding: utf-8

import logging
import json

from flask import Flask, request, g, abort
from werkzeug.utils import import_string
from httpdns.config import HTTPDNS_USER_COOKIE, IS_ADMIN

blueprints = (
    'index',
    'login',
)


def create_app():
    app = Flask(__name__)
    app.config.from_object('httpdns.config')
    app.secret_key = 'xiaoliulaoshibobobo'

    logging.basicConfig(format='%(levelname)s:%(asctime)s:%(message)s',
                        level=logging.INFO)

    for bp in blueprints:
        import_name = '%s.views.%s:bp' % (__package__, bp)
        app.register_blueprint(import_string(import_name))

    @app.before_request
    def init_global_vars():
        user_dict = json.loads(request.cookies.get(HTTPDNS_USER_COOKIE, '{}'))
        user = user_dict.get('realname')
        admins = IS_ADMIN.split(',')
        if user and user in admins:
            g.user = user
        else:
            g.user = None
    
    return app

httpdns/views/index.py
# encoding: utf-8

import sys 
import json
from flask import url_for, redirect, g, render_template, Blueprint, request, abort
from collections import defaultdict

from httpdns.db import rds
from httpdns.model import DomainName, Service_IP
from httpdns.config import DEFAULT_CACHE_TIME
from httpdns.consts import HTTPDNS_IP_DEFAULT, HTTPDNS_DOMAIN_PREFIX, DEFAULT_SP_NUM, SP_NUM_MAP

bp = Blueprint('index', __name__)
reload(sys) 
sys.setdefaultencoding('utf-8')

@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        domain = ''.join(request.form.get('host', default='').split())
        ip = ''.join(request.form.get('ip', default='').split())
        domain_name = DomainName(domain)
        if len(domain) != 0 and len(ip) != 0:
            domain_name.add(ip)
    domains = rds.smembers(HTTPDNS_DOMAIN_PREFIX)
    default_ip = rds.smembers(HTTPDNS_IP_DEFAULT)
    listip = []
    if default_ip:
        for ip in default_ip:
            listip.append(ip)
    TTL = DEFAULT_CACHE_TIME
    if not domains:
        domains = "0"
    count = {}
    for domain in domains:
        domain_name = DomainName(domain)
        count[domain] = domain_name.get_all_counts()
    return render_template('index.html', ttl=TTL, count=count, results=domains, default_ip=listip)

@bp.route('/default/', methods=['GET', 'POST'])
def default():
    if request.method == 'POST':
        ip = ''.join(request.form.get('defaultip', default='').split())
        default_ip = Service_IP(ip)
        if len(ip) != 0:
            default_ip.sadd_default_ip(ip)

    domains = rds.smembers(HTTPDNS_DOMAIN_PREFIX)
    default_ip = rds.smembers(HTTPDNS_IP_DEFAULT)
    TTL = DEFAULT_CACHE_TIME
    listip = []
    if default_ip:
        for ip in default_ip:
            listip.append(ip)
    if not domains:
        domains = "0"
    count = {}
    for domain in domains:
        domain_name = DomainName(domain)
        count[domain] = domain_name.get_all_counts()
    return render_template('index.html', ttl=TTL, count=count, results=domains, default_ip=listip)

@bp.route('/<domain>/', methods=['GET', 'POST'])
def show_info(domain):
    domain_name = DomainName(domain)
    if request.method == 'POST':
        isp = ''.join(request.form.get('local', default='').split())
        ip = ''.join(request.form.get('ip', default='').split())
        if len(ip) != 0 and len(isp) != 0:
            domain_name.add(ip, isp)
    count = domain_name.get_counts()
    result = defaultdict(list)
    for sp in domain_name.all_sps():
        for host in domain_name.sp_ips(sp):
            result[sp].append(host)
    if not result:
        return render_template('404.html')
    return render_template('domaininfo.html', count=count, results=result, domain=domain, spnummap=SP_NUM_MAP)

@bp.route('/delete/<domain>/<isp>/<ip>', methods=['POST'])
def delete_info(domain, isp, ip):
    domain_name = DomainName(domain)
    if rds.scard(('%s:%s:%s')%(HTTPDNS_DOMAIN_PREFIX, domain, isp)) == 1:
        domain_name.delete_sp(isp)
    domain_name.delete_sp_ip(ip, isp)
    result = defaultdict(list)
    for sp in domain_name.all_sps():
        for host in domain_name.sp_ips(sp):
            result[sp].append(host)
    return render_template('domaininfo.html', result=result, domain=domain)

@bp.route('/delete/<domain>', methods=['POST'])
def delete_domain(domain):
    domain_name = DomainName(domain)
    domain_name.delete_domain()
    result = defaultdict(list)
    for sp in domain_name.all_sps():
        for host in domain_name.sp_ips(sp):
            result[sp].append(host)
    return render_template('index.html', result=result)

@bp.route('/delete/<request_addr>', methods=['POST'])
def delete_request_addr(request_addr):
    print 1
    rds.srem(HTTPDNS_IP_DEFAULT, request_addr)
    domains = rds.smembers(HTTPDNS_DOMAIN_PREFIX)
    default_ip = rds.smembers(HTTPDNS_IP_DEFAULT)
    TTL = DEFAULT_CACHE_TIME
    listip = []
    if default_ip:
        for ip in default_ip:
            listip.append(ip)
    if not domains:
        domains = "0"
    count = {}
    for domain in domains:
        domain_name = DomainName(domain)
        count[domain] = domain_name.get_all_counts()
    return render_template('index.html', ttl=TTL, count=count, results=domains, default_ip=list_ip)

@bp.errorhandler(403)
@bp.errorhandler(404)
def errorhandler(error):
    return render_template('{}.html'.format(error.code))

#@bp.before_request
#def login_or_not():
#    if not g.user:
#        abort(403)

httpdns/views/login.py
#!/usr/bin/env python
# encoding: utf-8
import requests
import urllib
import urllib2
import json
from urlparse import urljoin
import flask
from flask import make_response, Blueprint, url_for, redirect, request, abort, jsonify, render_template
from httpdns.config import OPENID_SERVER_LOGIN, OPENID_SERVER_PRO, HTTPDNS_USER_COOKIE

bp = Blueprint('login', __name__,)

@bp.route('/login/')
def login():
    req_url = urllib.urlencode({
              'return_to': urljoin(request.url, url_for('login.verify')),
              'days': '14',
                              })
    url = "{0}?{1}".format(OPENID_SERVER_LOGIN, req_url)
    return redirect(url)

@bp.route('/verify/')
def verify():
    req_url = OPENID_SERVER_PRO + '?'
    token = request.args.get('token')
    params = {'token' : token}
    r = requests.get(req_url, params=params)
    resp = make_response(redirect(url_for('index.index')))
    if r.status_code == 200:
        try:
            profile = r.json()
        except ContentDecodingError:
            pass
        else:
            cookies = {'username': profile['username'], 'uid': profile['uid'],\
                    'email': profile['email'], 'realname':profile['realname']}
            resp.set_cookie(HTTPDNS_USER_COOKIE, json.dumps(cookies))
    return resp

@bp.route('/logout/')
def logout():
    resp = make_response(redirect(url_for('index.index')))
    if request.cookies.get(HTTPDNS_USER_COOKIE):
        resp.set_cookie(HTTPDNS_USER_COOKIE, '', expires=0)
    return resp 

httpdns/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>HTTPdns</title>
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/demo.css">
    <link href="/static/css/common.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">HTTPdns</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li> {% if not g.user %}
                 <a href='{{ url_for('login.login') }}'>登陆</a>
                 {% else %}
                 <a href='#' class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user" aria-hidden="true"> Welcome,{{ g.user }}</span></a>
                 <ul class='dropdown-menu'>
                   <li><a href='{{ url_for('login.logout') }}'><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> logout</a></li>
                 </ul> 
                 {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class='main-width'>{% block body %}{% endblock %}</div>
  </body>
</html>

httpdns/templates/domaininfo.html
<!DOCTYPE html>
{% extends "./base.html" %}
{% block head %}
{% endblock%}
{% block body %}
<form method="POST">
  <div class="panel panel-primary">
    <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> DomainName: {{ domain }}</div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Service Provider</th>
          <th>IP</th>
        </tr>
      </thead>
      <tbody>
      {% for result in results|sort %}
      <tr>
        <td>{{ spnummap[result] }}({{ result }})</td>
        <td>
          {% for ip in results[result]|sort %}
          {{ ip }}
          <input type='hidden' id='a' name='resultvalue' value={{ domain }}>
          <div href="{{ url_for('index.delete_info', domain=domain, isp=result, ip=ip)}}" class="btn btn-danger" style="float:right">
              <span>Delete</span>
          </div> 
          <br>
          <br>
          {% endfor %}
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <div class="input-group">
        <span class="input-group-addon" id="sizing-addon1"> isp</span>
          <input type="text" name="local" class="form-control" placeholder="如:1,2,...(isp编号)" aria-describedby="sizing-addon1">
      </div> 
    </div>
    <div class="col-xs-4">
      <div class="input-group">
        <span class="input-group-addon" id="sizing-addon2"> IP</span>
          <input type="text" name="ip" class="form-control" placeholder="如:192.168.0.1" aria-describedby="sizing-addon2">
      </div>
    </div>
    <div class="col-xs-2">
      <button class="btn btn-primary" name="add" value="addvalue" type="submit"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> ADD isp&ip</button>
    </div>
    <div class="col-xs-2">
      <button class="btn btn-info" id="return"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 返回上一页</button>
    </div>
  </div>
  <button class="btn btn-warning" id="button" onclick="help()">点此处查看isp编号与其对应关系</button></br>
  <div class="alert alert-info" role="alert" id="help">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>   
    {% for result in spnummap|sort %}
    <{{ result }}: {{ spnummap[result] }}>
    {% endfor %}
  </div>

<script type="text/javascript">
$('.btn-danger').click(function(){
    var url = $('#a').val();
    var self = $(this);
    href = self.attr('href');
    if (!confirm('确定要删除么?')) {
        return;
    }else{
      $.post(href, {}, function(){
        window.location.href = '/'+ url;
      });
    }
});
$('#return').click(function(){
    var self = $(this);
    href = self.attr('href');
    $.post(href, {}, function(){
        window.location.href = "{{ url_for('index.index') }}"
    });
});
function help()
{
    help.style.display='';
}
</script>
</form>
{% endblock %}

httpdns/templates/index.html
<!DOCTYPE html>
{% extends "./base.html" %}
{% block head %}
{% endblock %}
{% block body %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
    <strong> HTTPDNS Control</strong>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Domain Name</th>
        <th style="text-align:right">Operating</th>
      </tr>
    </thead>
    <tbody>
      {% for result in results %}
      <tr>
        <td><a href={{ url_for('index.index') + result }}>{{ result }}</a></td>
        <td>
          <div href="{{ url_for('index.delete_domain', domain=result) }}" class="btn btn-danger" style="float:right">
            <span>Delete</span>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="panel panel-info">
  <div class="panel-heading"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span><strong> Setting</strong></div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Time To Live</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ ttl }} ms</td>
      </tr>
    </tbody>
  </table>
</div>
<div class="panel panel-info">
    <div class="panel-heading"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span><strong> Request Addr</strong></div>
    <table class="table table-striped">
      <tbody>
        {% for request in default_ip %}
          <tr>
            <td>{{ request }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

<form method="POST" class='form-inline' action='/'>
  <div class="panel panel-primary">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>DomainName</th>
          <th>IP</th>
          <th style="text-align:right">Operation</th>
       </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div class="input-group">
                <span class="input-group-addon" id="sizing-addon1"> 域名</span>
                <input type="text" name="host" class="form-control" placeholder="www.hunantv.com" aria-describedby="sizing-addon1">
            </div>     
          </td>
          <td>
            <div class="input-group">
              <span class="input-group-addon" id="sizing-addon2"> IP</span>
              <input type="text" name="ip" class="form-control" placeholder="如:192.168.0.1" aria-describedby="sizing-addon2">
            </div>     
          </td>
          <td>
            <button class="btn btn-primary" id="add" type="submit"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> ADD DomainName</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</form>
<form method="POST" class='form-inline' action='/default/'>
  <div class="panel panel-primary">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>SET Request addr</th>
          <th style="text-align:right">Operation</th>
       </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div class="input-group">
                <span class="input-group-addon" id="sizing-addon3"> 备用IP</span>
                <input type="text" name="defaultip" class="form-control" placeholder="如：192.168.2.4" aria-describedby="sizing-addon3">
            </div>     
          </td>
          <td>
            <button class="btn btn-primary" id="add" type="submit"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add/Modify Request addr</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</form>

</body>
<script>
$('.btn-danger').click(function(e){
     var self = $(this);
     href = self.attr('href');
     if (!confirm('确定要删除么?')) {
         return;
     }else{
       $.post(href, {}, function(){
         window.location.href = '/';
       });
     }
 });
</script>
{% endblock %}